version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/tomcatstop.sh
      timeout: 300
      runas: root
  ValidateService: 
    - location: scripts/backup.sh
      runas: root
      timeout: 60

